import {NextResponse} from 'next/server';
import {requireUser} from '../../../../lib/supabase-server';
import {parseEmail} from '../../../../lib/email-parser';
function isoDate(x){try{return x?new Date(x).toISOString().slice(0,10):null}catch{return null}}
async function contractorId(sb,name){if(!name)return null;const {data}=await sb.from('contractors').select('id').ilike('name',name).maybeSingle();return data?.id||null}
async function transmittalId(sb,p,m,cid){if(!p.transmittal)return null;const payload={transmittal_number:p.transmittal,contractor_id:cid,transmittal_date:isoDate(m.received),outlook_email_web_link:null,email_subject:m.subject,email_sender:m.sender||null,direction:p.returnCode?'RETURN':'SUBMISSION'};const {data}=await sb.from('transmittals').upsert(payload,{onConflict:'transmittal_number'}).select('id').single();return data?.id||null}
async function applyRegister(sb,m,p,emailId){if(!p.documents.length)return{applied:0,needs:p.isRelevant?1:0};let applied=0,needs=0;const cid=await contractorId(sb,p.contractor);const tid=await transmittalId(sb,p,m,cid);for(const docno of p.documents){let {data:d}=await sb.from('documents').select('id').eq('document_number',docno).maybeSingle();if(!d){const ins=await sb.from('documents').insert({document_number:docno,document_title:p.documentTitles?.[docno]||null,contractor_id:cid}).select('id').single();if(ins.error){needs++;continue}d=ins.data}if(p.returnCode){let q=sb.from('document_revisions').select('id').eq('document_id',d.id);if(p.revision)q=q.eq('revision',p.revision);const {data:rv}=await q.order('submitted_date',{ascending:false}).limit(1).maybeSingle();if(!rv){needs++;continue}await sb.from('document_revisions').update({return_transmittal_id:tid,returned_date:isoDate(m.received),return_code:p.returnCode,return_email_id:emailId,needs_review:p.confidence!=='HIGH'}).eq('id',rv.id);applied++}else if(p.stage&&p.revision){const payload={document_id:d.id,revision:p.revision,issue_status:p.stage,submission_transmittal_id:tid,submitted_date:isoDate(m.received),submission_email_id:emailId,needs_review:p.confidence!=='HIGH'};const {error}=await sb.from('document_revisions').upsert(payload,{onConflict:'document_id,revision,issue_status'});if(error)needs++;else applied++}else needs++}return{applied,needs}}
export async function POST(request){try{const {sb,user,profile}=await requireUser(request);if(!['SUPER_ADMIN','ADMIN'].includes(profile.role))return NextResponse.json({error:'Admin access required'},{status:403});const {messages=[]}=await request.json();let scanned=0,relevant=0,applied=0,needs=0;for(const m of messages.slice(0,100)){scanned++;const graphShape={subject:m.subject||'',bodyPreview:m.body||'',from:{emailAddress:{address:m.sender||''}},receivedDateTime:m.received||null};const attachments=(m.attachmentNames||[]).map(name=>({name}));const p=parseEmail(graphShape,attachments);if(p.isRelevant)relevant++;const stable=m.messageId||`${m.received||''}|${m.sender||''}|${m.subject||''}`;const graphId=`pst:${Buffer.from(stable).toString('base64url').slice(0,180)}`;const payload={user_id:user.id,graph_message_id:graphId,internet_message_id:m.messageId||null,subject:m.subject||null,sender_email:(m.sender||'').toLowerCase()||null,recipient_emails:[m.to,m.cc].filter(Boolean),received_at:m.received||null,web_link:null,is_relevant:p.isRelevant,parse_confidence:p.confidence,parsed_data:{...p,source:m.source||'PST',folder:m.folderName||null,sourceFile:m.sourceFile||null},import_source:m.source||'PST',source_folder:m.folderName||null,updated_at:new Date().toISOString()};const {data:em,error}=await sb.from('email_messages').upsert(payload,{onConflict:'user_id,graph_message_id'}).select('id').single();if(!error&&p.isRelevant){const r=await applyRegister(sb,m,p,em.id);applied+=r.applied;needs+=r.needs}}
return NextResponse.json({scanned,relevant,register_updates:applied,needs_review:needs});}catch(e){return NextResponse.json({error:e.message},{status:400})}}
