"use client";
import {useEffect,useMemo,useState} from "react";
import {sb} from "../lib/supabase-browser";
import {exportRows} from "../lib/exportExcel";
import {readPst} from "../lib/pst-import";
import {readMsgFile,filterMsgFiles} from "../lib/msg-import";

const ISSUE={IFR:"Issued for Review",IFA:"Issued for Approval",IFC:"Issued for Construction",IFU:"Issued for Use",IFI:"Issued for Information",IFD:"Issued for Design",IFP:"Issued for Purchase",RLM:"Red-Line Markup / In-House",AB:"As-Built"};
const CODE={"1":"Approved","2":"Approved with Comments","3":"Rejected","4":"For Information Only"};

export default function Page(){
 const supabase=sb();
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[profile,setProfile]=useState(null);
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[view,setView]=useState("Dashboard"),[rows,setRows]=useState([]),[contractors,setContractors]=useState([]);
 const [contractor,setContractor]=useState(""),[discipline,setDiscipline]=useState(""),[year,setYear]=useState(""),[issue,setIssue]=useState(""),[q,setQ]=useState("");
 const [syncing,setSyncing]=useState(false),[syncMsg,setSyncMsg]=useState(""),[selectedPst,setSelectedPst]=useState(null),[readPct,setReadPct]=useState(0),[pstProgress,setPstProgress]=useState({parsed:0,processed:0,total:0,relevant:0,updates:0,needs:0});
 const [msgFiles,setMsgFiles]=useState([]);
 const [audit,setAudit]=useState({attachments:0,nested:0,events:0,submissions:0,returns:0,unknown:0,failed:0});

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:s}=supabase.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>s.subscription.unsubscribe()},[]);
 async function loadData(){if(!session)return;const [p,r,c]=await Promise.all([supabase.from("profiles").select("*").eq("id",session.user.id).single(),supabase.from("document_register_v").select("*").order("submitted_date",{ascending:false}).limit(10000),supabase.from("contractors").select("name").eq("is_active",true).order("name")]);setProfile(p.data);setRows(r.data||[]);setContractors((c.data||[]).map(x=>x.name));}
 async function importPst(file=selectedPst){
   if(!file)return; setSyncing(true); setReadPct(0); setSyncMsg("Reading PST directly in your browser — the PST itself is never uploaded to Vercel or Supabase."); setPstProgress({parsed:0,processed:0,total:0,relevant:0,updates:0,needs:0});
   try{
     const messages=await readPst(file,p=>{
       if(p?.stage==='reading'){const pct=p.totalBytes?Math.min(100,Math.round((p.bytes/p.totalBytes)*100)):0;setReadPct(pct);setSyncMsg(`Reading ${file.name}… ${pct}%`);}
       if(p?.stage==='opening')setSyncMsg('PST file read successfully. Opening Outlook data…');
       if(p?.stage==='parsing'){setPstProgress(x=>({...x,parsed:p.messages||0}));setSyncMsg(`Scanning Outlook folders… ${p.messages||0} emails detected`);}
     });
     setReadPct(100); setPstProgress(x=>({...x,total:messages.length,parsed:messages.length}));
     let processed=0,relevant=0,updates=0,needs=0;
     for(let i=0;i<messages.length;i+=25){
       const batch=messages.slice(i,i+25);
       const r=await fetch('/api/pst/import',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},body:JSON.stringify({messages:batch})});
       const j=await r.json(); if(!r.ok)throw new Error(j.error||'Import failed');
       processed+=j.scanned||0; relevant+=j.relevant||0; updates+=j.register_updates||0; needs+=j.needs_review||0;
       setPstProgress({parsed:messages.length,total:messages.length,processed,relevant,updates,needs}); setSyncMsg(`Importing extracted metadata… ${processed} / ${messages.length}`);
       await new Promise(resolve=>setTimeout(resolve,20));
     }
     setSyncMsg(`Historical import complete: ${processed} emails scanned, ${relevant} relevant DCC emails, ${updates} register updates, ${needs} need review.`); await loadData();
   }catch(e){setSyncMsg(`Import stopped: ${e.message}`)}finally{setSyncing(false)}
 }

 async function importMsgFolder(files){
   const list=filterMsgFiles(files); if(!list.length){setSyncMsg('No Outlook .msg files were found in the selected folder.');return}
   setSyncing(true);setReadPct(0);setPstProgress({parsed:0,processed:0,total:list.length,relevant:0,updates:0,needs:0});setAudit({attachments:0,nested:0,events:0,submissions:0,returns:0,unknown:0,failed:0});setSyncMsg(`Deep attachment audit: ${list.length} Outlook messages selected. MDCT will inspect every direct attachment plus ZIP and attached-message contents.`);
   let processed=0,relevant=0,updates=0,needs=0,failed=0,attachments=0,nested=0,events=0,submissions=0,returns=0,unknown=0;let batch=[];
   try{
     for(let i=0;i<list.length;i++){
       try{const m=await readMsgFile(list[i]);batch.push(m)}catch{failed++}
       setReadPct(Math.round(((i+1)/list.length)*100));setPstProgress(x=>({...x,parsed:i+1,total:list.length}));
       if(batch.length>=20||i===list.length-1){
         if(batch.length){const r=await fetch('/api/pst/import',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},body:JSON.stringify({messages:batch})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Import failed');processed+=j.scanned||0;relevant+=j.relevant||0;updates+=j.register_updates||0;needs+=j.needs_review||0;attachments+=j.attachments_found||0;nested+=j.nested_attachments||0;events+=j.document_events||0;submissions+=j.submission_emails||0;returns+=j.return_emails||0;unknown+=j.unknown_direction||0;batch=[];setPstProgress({parsed:i+1,total:list.length,processed,relevant,updates,needs});setAudit({attachments,nested,events,submissions,returns,unknown,failed});}
         setSyncMsg(`Deep audit: ${i+1}/${list.length} emails read · ${attachments.toLocaleString()} direct attachments · ${nested.toLocaleString()} nested/ZIP items · ${events.toLocaleString()} document events recognized · ${failed} unreadable.`);await new Promise(resolve=>setTimeout(resolve,0));
       }
     }
     setAudit({attachments,nested,events,submissions,returns,unknown,failed});setSyncMsg(`Deep historical audit complete: ${processed} emails analyzed · ${attachments.toLocaleString()} direct attachments · ${nested.toLocaleString()} nested/ZIP items · ${events.toLocaleString()} document events · ${updates.toLocaleString()} register updates · ${needs.toLocaleString()} need review.`);await loadData();
   }catch(e){setSyncMsg(`Import stopped: ${e.message}`)}finally{setSyncing(false)}
 }

 const disciplines=useMemo(()=>[...new Set(rows.map(r=>r.discipline_name).filter(Boolean))].sort(),[rows]);
 const years=useMemo(()=>[...new Set(rows.map(r=>r.submitted_date?.slice(0,4)).filter(Boolean))].sort().reverse(),[rows]);
 const f=useMemo(()=>rows.filter(r=>(!contractor||r.contractor_name===contractor)&&(!discipline||r.discipline_name===discipline)&&(!year||r.submitted_date?.startsWith(year))&&(!issue||r.issue_status===issue)&&(!q||[r.document_number,r.document_title,r.submission_transmittal,r.return_transmittal].join(" ").toLowerCase().includes(q.toLowerCase()))),[rows,contractor,discipline,year,issue,q]);
 const k={total:f.length,review:f.filter(r=>r.status==="UNDER REVIEW").length,over:f.filter(r=>r.status==="OVERDUE").length,ret:f.filter(r=>r.status==="RETURNED").length,c1:f.filter(r=>r.return_code===1).length,c2:f.filter(r=>r.return_code===2).length,c3:f.filter(r=>r.return_code===3).length,c4:f.filter(r=>r.return_code===4).length};
 const dd=useMemo(()=>{const m={};f.forEach(r=>m[r.discipline_name||"Unassigned"]=(m[r.discipline_name||"Unassigned"]||0)+1);return Object.entries(m).sort((a,b)=>b[1]-a[1])},[f]); const max=Math.max(1,...dd.map(x=>x[1]));
 const monthly=useMemo(()=>{const m={};f.forEach(r=>{if(r.submitted_date){const x=r.submitted_date.slice(0,7);m[x]=(m[x]||0)+1}});return Object.entries(m).sort((a,b)=>a[0].localeCompare(b[0])).slice(-18)},[f]);const maxM=Math.max(1,...monthly.map(x=>x[1]));

 if(loading)return <div className="login">Loading…</div>;
 if(!session)return <div className="login"><form className="card loginCard" onSubmit={async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)alert(error.message)}}><img src="/miran-energy-logo.png" alt="Miran Energy Ltd" className="loginLogo"/><h2>Miran Document Control Tracker</h2><div className="small">Authorized users only</div><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn" style={{marginTop:10,width:"100%"}}>Sign in</button></form></div>;

 const filters=<div className="filters"><select value={contractor} onChange={e=>setContractor(e.target.value)}><option value="">All Contractors</option>{contractors.map(x=><option key={x}>{x}</option>)}</select><select value={discipline} onChange={e=>setDiscipline(e.target.value)}><option value="">All Disciplines</option>{disciplines.map(x=><option key={x}>{x}</option>)}</select><select value={year} onChange={e=>setYear(e.target.value)}><option value="">All Years</option>{years.map(x=><option key={x}>{x}</option>)}</select><select value={issue} onChange={e=>setIssue(e.target.value)}><option value="">All Issue Statuses</option>{Object.entries(ISSUE).map(([kk,v])=><option value={kk} key={kk}>{kk} — {v}</option>)}</select></div>;
 const table=<div className="panel"><div className="filters"><input placeholder="Search…" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn" onClick={()=>exportRows(f)}>Export Excel</button></div><div className="tablewrap"><table><thead><tr><th>Contractor</th><th>Document Number</th><th>Title</th><th>Facility</th><th>TSS</th><th>Discipline</th><th>Doc Type</th><th>Rev</th><th>Issue Status</th><th>Submission</th><th>Submitted</th><th>Due</th><th>Return</th><th>Code</th><th>Return Status</th><th>Review Status</th><th>Email</th></tr></thead><tbody>{f.map(r=><tr key={r.revision_id}><td>{r.contractor_name}</td><td><b>{r.document_number}</b></td><td>{r.document_title}</td><td>{r.facility_code}</td><td>{r.train_system_code}</td><td>{r.discipline_code} — {r.discipline_name}</td><td>{r.document_type_code}</td><td>{r.revision}</td><td>{r.issue_status}</td><td>{r.submission_transmittal}</td><td>{r.submitted_date}</td><td>{r.due_date}</td><td>{r.return_transmittal}</td><td>{r.return_code?`Code-${r.return_code}`:""}</td><td>{r.return_status}</td><td><span className={`badge ${r.status==="OVERDUE"?"bad":r.status==="RETURNED"?"good":"warn"}`}>{r.status}</span></td><td>{r.email_web_link?<a href={r.email_web_link} target="_blank">Open Email</a>:""}</td></tr>)}</tbody></table></div></div>;
 const nav=["Dashboard","Document Register","Historical Import","Numbering Rules","Revision Workflow"];
 return <div className="shell"><aside className="side"><b>MIRAN ENERGY</b>{nav.map(n=><button className={view===n?"active":""} onClick={()=>setView(n)} key={n}>{n}</button>)}<button onClick={()=>supabase.auth.signOut()}>Logout</button></aside><main className="main"><div className="top"><div><h2>{view}</h2><div className="small">Aligned to Miran Document Numbering Procedure</div></div><div className="small">{profile?.email} · {profile?.role}</div></div>
 {view!=="Historical Import"&&filters}
 {view==="Dashboard"&&<><div className="kpis kpis8">{[["TOTAL",k.total],["UNDER REVIEW",k.review],["OVERDUE",k.over],["RETURNED",k.ret],["CODE-1",k.c1],["CODE-2",k.c2],["CODE-3",k.c3],["CODE-4",k.c4]].map(x=><div className="kpi" key={x[0]}><div className="small">{x[0]}</div><b>{x[1]}</b></div>)}</div><div className="grid2"><div className="panel"><b>Submissions by Discipline</b>{dd.map(([n,c])=><div className="bar" key={n}><span>{n}</span><div className="track"><div className="fill" style={{width:`${c/max*100}%`}}/></div><b>{c}</b></div>)}</div><div className="panel"><b>Submissions by Month</b>{monthly.map(([n,c])=><div className="bar" key={n}><span>{n}</span><div className="track"><div className="fill" style={{width:`${c/maxM*100}%`}}/></div><b>{c}</b></div>)}</div></div>{table}</>}
 {view==="Document Register"&&table}
 {view==="Historical Import"&&<div className="panel syncPanel"><div className="syncHead"><div><h3>Historical Outlook Import</h3><div className="small">No Microsoft Graph or Miran domain-admin approval required. MDCT stores only extracted metadata in Supabase.</div></div><span className="badge good">NO MICROSOFT ADMIN REQUIRED</span></div>
 <div className="panel inner"><h3>Option A — Standard PST</h3><div className="small">Use this only for PST files up to 750 MB. Large multi-GB PST files cannot be safely loaded into a normal browser memory space.</div><div className="uploadBox"><input type="file" accept=".pst,application/vnd.ms-outlook" disabled={syncing} onChange={e=>{const file=e.target.files?.[0]||null;setSelectedPst(file);setSyncMsg(file?`${file.name} selected (${(file.size/1024/1024).toFixed(1)} MB).`:'');setReadPct(0);setPstProgress({parsed:0,processed:0,total:0,relevant:0,updates:0,needs:0});}}/>{selectedPst&&<div className="fileReady"><b>{selectedPst.name}</b><span>{(selectedPst.size/1024/1024).toFixed(1)} MB</span>{selectedPst.size<=750*1024*1024?<button className="btn" disabled={syncing} onClick={()=>importPst(selectedPst)}>{syncing?'Processing…':'Start PST Analysis'}</button>:<span className="badge warn">USE LARGE ARCHIVE MODE BELOW</span>}</div>}</div></div>
 <div className="panel inner"><h3>Option B — Deep Attachment Audit (recommended for your 5.14 GB history)</h3><p><b>Designed for Lazo document-control history.</b> MDCT treats each email as a container and inspects <b>every attachment separately</b>. It also looks inside ZIP files and attached Outlook messages for additional document filenames. The user-confirmed Miran pattern is applied as a strong direction signal: <b>Lazo + “Dear colleagues” → vendor submission/internal circulation</b>; <b>Lazo without “Dear colleagues” + return/review wording or Code-1…4 → return to contractor</b>. Uncertain cases are marked Needs Review rather than guessed.</p><div className="uploadBox"><input type="file" multiple webkitdirectory="" directory="" disabled={syncing} onChange={e=>{const files=filterMsgFiles(e.target.files);setMsgFiles(files);setSyncMsg(files.length?`${files.length} Outlook .msg files selected. Click Start Deep Attachment Audit.`:'No .msg files found in that folder.');setReadPct(0);setPstProgress({parsed:0,processed:0,total:files.length,relevant:0,updates:0,needs:0});setAudit({attachments:0,nested:0,events:0,submissions:0,returns:0,unknown:0,failed:0});}}/>{msgFiles.length>0&&<div className="fileReady"><b>{msgFiles.length.toLocaleString()} Outlook messages</b><span>every attachment audited</span><button className="btn" disabled={syncing} onClick={()=>importMsgFolder(msgFiles)}>{syncing?'Processing…':'Start Deep Attachment Audit'}</button></div>}</div></div>
 {syncing&&<div className="readProgress"><div style={{width:`${readPct}%`}}/><span>{readPct}%</span></div>}<div className="syncGrid"><div><div className="small">Emails Detected</div><b>{pstProgress.total||pstProgress.parsed}</b></div><div><div className="small">Processed</div><b>{pstProgress.processed}</b></div><div><div className="small">Relevant DCC</div><b>{pstProgress.relevant}</b></div><div><div className="small">Register Updates</div><b>{pstProgress.updates}</b></div><div><div className="small">Needs Review</div><b>{pstProgress.needs}</b></div></div><div className="syncGrid auditGrid"><div><div className="small">Direct Attachments</div><b>{audit.attachments.toLocaleString()}</b></div><div><div className="small">Inside ZIP / Attached MSG</div><b>{audit.nested.toLocaleString()}</b></div><div><div className="small">Document Events Found</div><b>{audit.events.toLocaleString()}</b></div><div><div className="small">Submission Emails</div><b>{audit.submissions.toLocaleString()}</b></div><div><div className="small">Return Emails</div><b>{audit.returns.toLocaleString()}</b></div></div>{syncMsg&&<div className="notice">{syncMsg}</div>}<div className="panel inner"><b>Deep inspection rules in V3.3</b><p>Each .msg email is audited attachment-by-attachment. PDF/DWG/DOC/DOCX/XLS/XLSX filenames are parsed individually; ZIP contents and attached .msg messages are opened in browser memory so document filenames inside them are also counted. Image signatures/logos are ignored. Raw emails and documents are not stored. Direction is classified using sender, recipients, wording, return code and your Lazo “Dear colleagues” workflow pattern. Low-confidence matches go to Needs Review.</p></div></div>}
 {view==="Numbering Rules"&&<div className="grid2"><div className="panel"><h3>Engineering</h3><p><b>MR-FAC-TSS-XX-XXX-0000</b></p><p>MR = Project Code</p><p>FAC = EPF / SRU / BPP / WP2</p><p>TSS = 1-digit Train + 2-digit System</p><p>XX = Discipline</p><p>XXX = Document Type</p><p>0000 = Sequence</p></div><div className="panel"><h3>Vendor</h3><p><b>MR-FAC-TSS-EQ-XX-XXX-0000</b></p><p>Adds Equipment Code before Discipline.</p></div></div>}
 {view==="Revision Workflow"&&<div className="grid2"><div className="panel"><h3>Revision Families</h3><p><b>A</b> → IFR</p><p><b>B,C,D…</b> → IFA / reissue logic</p><p><b>0,1,2…</b> → IFC / IFU / IFI / IFD / IFP</p><p><b>0.1,1.1…</b> → RLM</p><p><b>AB1,AB2…</b> → AB</p></div><div className="panel"><h3>Return Codes</h3>{Object.entries(CODE).map(([kk,v])=><p key={kk}><b>Code-{kk}</b> — {v}</p>)}</div></div>}
 </main></div>;
}
